---
- name: include variables
  include_vars: "{{ lighttpd_fqdn }}.yml"

- name: Install Lighttpd
  yum:
    name: lighttpd
    state: latest
  register: lighttpd_installed

- name: certificate
  when: lighttpd_installed|success
  copy:
    content: "{{ cert }}"
    dest: /etc/lighttpd/server.pem
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: main config
  when: lighttpd_installed|success
  template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: vhost config
  when: lighttpd_installed|success
  template:
    src: "{{ lighttpd_fqdn }}.conf.j2"
    dest: "/etc/lighttpd/conf.d/{{ lighttpd_fqdn }}.conf"
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: Start and enable Lighttpd
  when: lighttpd_installed|success
  service:
    name: lighttpd
    enabled: yes
    state: started
