---
- name: include variables
  include_vars: "{{ lighttpd_fqdn }}.yml"

- name: Install Lighttpd
  yum:
    name: lighttpd
    state: latest
  register: lighttpd_installed

- name: Install Lighttpd CGI
  yum:
    name: lighttpd-fastcgi
    state: latest

- name: certificate
  when: lighttpd_installed is success
  copy:
    content: "{{ cert }}"
    dest: /etc/lighttpd/server.pem
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: main config
  when: lighttpd_installed is success
  template:
    src: lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: access_log config
  when: lighttpd_installed is success
  copy:
    src: access_log.conf
    dest: /etc/lighttpd/conf.d/access_log.conf
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: vhost config
  when: lighttpd_installed is success
  template:
    src: "{{ lighttpd_fqdn }}.conf.j2"
    dest: "/etc/lighttpd/conf.d/{{ lighttpd_fqdn }}.conf"
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: Start and enable Lighttpd
  when: lighttpd_installed is success
  service:
    name: lighttpd
    enabled: yes
    state: started

- name: HTTP root dir
  file:
    name: "/srv/http/{{ lighttpd_fqdn }}"
    state: directory
    owner: lighttpd
    group: lighttpd

