---
- name: include variables
  include_vars: "{{ lighttpd_fqdn }}.yml"

- name: Install Lighttpd
  yum:
    name: lighttpd
    state: latest
  register: lighttpd_installed

- name: certificate
  when: lighttpd_installed|success
  copy:
    content: "{{ cert }}"
    dest: /etc/lighttpd/server.pem
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: main config
  when: lighttpd_installed|success
  copy:
    src: lighttpd.conf
    dest: /etc/lighttpd/lighttpd.conf
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: rss config
  when: lighttpd_installed|success
  copy:
    src: rss.conf
    dest: /etc/lighttpd/conf.d/rss.conf
    owner: lighttpd
    group: lighttpd
  notify:
    - Reload Lighttpd

- name: Enable Lighttpd
  when: lighttpd_installed|success
  service:
    name: lighttpd
    enabled: yes
    state: started
