---
- hosts: rss-test
  vars:
    lighttpd_fqdn: rss-test.tomasdubec.com
    tt_rss_dir: /srv/http/rss-test.tomasdubec.com
  roles:
    - iptables
    - packages
    - lighttpd
    - php
    - mysql
    - tt-rss
