- name: Add EPEL config file
  copy:
    src: epel.repo
    dest: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
- name: Add EPEL key
  copy:
    src: RPM-GPG-KEY-EPEL-6
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
    owner: root
    group: root

- name: Add webtatic config file
  copy:
    src: webtatic.repo
    dest: /etc/yum.repos.d/webtatic.repo
    owner: root
    group: root
- name: Add webtatic key
  copy:
    src: RPM-GPG-KEY-webtatic-andy
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-webtatic-andy
    owner: root
    group: root
